// Writing prompts, keyed by occasion. The occasion picker lives inside the
// prompts dropdown (Design Guide Oct 2026) and shapes which prompts appear.
export const PROMPTS: Record<string, string[]> = {
  BIRTHDAY: [
    "The world got lucky when it got you because…",
    "I hope this year surprises you with…",
    "Today we celebrate you for…",
    "This year, you're officially old enough to…",
    "You're aging like…",
    "Today we celebrate your incredible talent for…",
    "You've somehow managed to become even more…",
    "This year, I hope you lean all the way into…",
    "You make ordinary things better just by…",
    "This is your year to fully own…",
    "I hope this new year brings you…",
    "You've grown in ways that are really clear when…",
    "You make life lighter just by…",
    "The world feels a little better with you in it because…",
  ],
  ANNIVERSARY: [
    "Looking back on our time together, what stands out most is:",
    "Every year with you feels like:",
    "You still make me feel:",
  ],
  CONGRATULATIONS: [
    "This is such a big deal because…",
    "You worked for this in ways people don't even see, like…",
    "This moment says so much about who you are…",
    "I can't wait to see what you do with…",
    "You're more ready for this than you think because…",
    "This next chapter is going to challenge you to…",
    "A strength you're bringing into this season…",
    "You should be really proud of yourself for…",
    "This is only the beginning of…",
    "I'll be right here cheering you on when…",
  ],
  HOLIDAY: [
    "This time of year always makes me think of:",
    "Wishing you the kind of holiday season that feels like:",
    "What I love most about celebrating with you is:",
  ],
  CONSOLATION: [
    "You don't have to have it all figured out right now, especially…",
    "I'm here for you in whatever way you need, even if that looks like…",
    "It makes sense that you feel…",
    "You're allowed to take your time with…",
    "I wish I could make this easier, but I can remind you…",
    "You're still you, even in the middle of…",
    "If today feels heavy, focus on…",
    "I see how strong you're being, especially when…",
    "You don't have to go through this quietly…",
    "I'm not going anywhere, even when…",
  ],
  JUST_BECAUSE: [
    "Something I don't say enough is…",
    "I really admire the way you…",
    "I don't say this enough, but…",
    "You've made my life better by…",
    "A moment I felt really grateful for you was…",
    "You make hard days easier by…",
    "I feel lucky to know you because…",
    "One thing about you that never goes unnoticed…",
    "You have a way of…",
    "If you ever forget, here's what makes you special…",
    "Remember when we thought it was a good idea to…",
    "The first time I knew we'd be friends was when…",
    "The way you show up for people is…",
    "You have the best taste in…",
    "I trust you with…",
    "You make things feel easier when…",
    "You're really good at noticing…",
    "I appreciate how you…",
    "You make ordinary moments better by…",
    "I'd be lying if I said I didn't…",
    "One thing I wish I told you sooner…",
    "Scientists should study you for your ability to…",
  ],
  INVITATION: [
    "You're invited! Here's what's happening:",
    "I'd love for you to be there because:",
    "It wouldn't be the same without you:",
  ],
  CUSTOM: [
    "I've been meaning to tell you:",
    "Here's something I want you to know:",
    "You deserve to hear this:",
  ],
}

export const OCCASIONS = [
  { value: 'JUST_BECAUSE', art: 'envelope', label: 'Just because' },
  { value: 'BIRTHDAY', art: 'cake', label: 'Birthday' },
  { value: 'CONGRATULATIONS', art: 'popper', label: 'Big moments' },
  { value: 'ANNIVERSARY', art: 'hearteyes', label: 'Anniversary' },
  { value: 'HOLIDAY', art: 'star', label: 'Holiday' },
  { value: 'CONSOLATION', art: 'rainbow', label: 'Hard times' },
  { value: 'INVITATION', art: 'plane', label: 'Invitation' },
]
